export const pokeneas = [
  {
    id: 1,
    name: 'Bulbasaur',
    height: '2.04',
    ability: 'Overgrow',
    image: 'https://pokeneas.s3.us-east-1.amazonaws.com/001.png',
    phrase: 'Get ready to be inspired…',
  },
  {
    id: 2,
    name: 'Ivysaur',
    height: '3.03',
    ability: 'Overgrow',
    image: 'https://pokeneas.s3.us-east-1.amazonaws.com/002.png',
    phrase: 'See rejection as redirection.',
  },
  {
    id: 3,
    name: 'Venusaur',
    height: '6.07',
    ability: 'Overgrow',
    image: 'https://pokeneas.s3.us-east-1.amazonaws.com/003.png',
    phrase: 'There is beauty in simplicity.',
  },
  {
    id: 4,
    name: 'Charmander',
    height: '2.00',
    ability: 'Blaze',
    image: 'https://pokeneas.s3.us-east-1.amazonaws.com/004.png',
    phrase: 'You can’t be late until you show up.',
  },
  {
    id: 5,
    name: 'Charmeleon',
    height: '3.00',
    ability: 'Blaze',
    image: 'https://pokeneas.s3.us-east-1.amazonaws.com/005.png',
    phrase: 'Maybe life is testing you. Don’t give up.',
  },
  {
    id: 6,
    name: 'Charizard',
    height: '6.00',
    ability: 'Blaze',
    image: 'https://pokeneas.s3.us-east-1.amazonaws.com/006.png',
    phrase: 'Impossible is just an opinion.',
  },
  {
    id: 7,
    name: 'Squirtle',
    height: '1.00',
    ability: 'Torrent',
    image: 'https://pokeneas.s3.us-east-1.amazonaws.com/007.png',
    phrase: 'Alone or not you gonna walk forward.',
  },
  {
    id: 8,
    name: 'Wartortle',
    height: '3.00',
    ability: 'Torrent',
    image: 'https://pokeneas.s3.us-east-1.amazonaws.com/008.png',
    phrase: "In a rich man's house there is no place to spit but his face.",
  },
  {
    id: 9,
    name: 'Blastoise',
    height: '6.00',
    ability: 'Torrent',
    image: 'https://pokeneas.s3.us-east-1.amazonaws.com/009.png',
    phrase: 'In the kingdom of the blind, the one-eyed man is king.',
  },
];